apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goat-api
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goat-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: goat-api
    spec:
      containers:
      - image: ${DOCKER_IMAGE}
        imagePullPolicy: IfNotPresent
        name: goat-api
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /ping
            port: 3000
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /ping
            port: 3000
          initialDelaySeconds: 20
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 3
        env:
          - name: APP_PORT
            value: '3000'
          - name: POSTGRES_USER
            value: ${POSTGRES_USER}
          - name: POSTGRES_HOST
            value: postgres.${NAMESPACE}.svc.cluster.local
          - name: POSTGRES_DBNAME
            value: ${POSTGRES_DB}
          - name: POSTGRES_PASS
            value: ${POSTGRES_PASSWORD}
          - name: POSTGRES_PORT
            value: '5432'
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: goat-api
  namespace: ${NAMESPACE}
spec:
  rules:
    - host: ${DOMAIN}
      http:
        paths:
          - backend:
              serviceName: goat-api
              servicePort: 80
            path: /api
  tls:
  - hosts:
    - ${DOMAIN}
    secretName: letsencrypt-prod
---
apiVersion: v1
kind: Service
metadata:
  name: goat-api
  namespace: ${NAMESPACE}
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app: goat-api
